-- Custom glyphs defined via the client patch pipeline.
-- GENERATED by tools/build_client_patch.py from tools/client_patch_manifest.json
-- (client side: wow-client/Data/patch-S.mpq). Do not edit by hand.

DELETE FROM `glyphproperties_dbc` WHERE `ID` IN (1501, 1502);
INSERT INTO `glyphproperties_dbc` (`ID`, `SpellID`, `GlyphSlotFlags`, `SpellIconID`) VALUES
    (1501, 200101, 1, 3125),
    (1502, 200102, 0, 3128);

DELETE FROM `spell_dbc` WHERE `ID` IN (200001, 200101, 200002, 200102);
INSERT INTO `spell_dbc`
    (`ID`, `Attributes`, `AttributesEx`, `Targets`, `InterruptFlags`, `ProcChance`,
     `CastingTimeIndex`, `DurationIndex`, `RangeIndex`, `EquippedItemClass`,
     `Effect_1`, `ImplicitTargetA_1`, `EffectAura_1`, `EffectMiscValue_1`,
     `SpellVisualID_1`, `SpellIconID`, `SchoolMask`, `Name_Lang_enUS`) VALUES
    (200001, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1501, 12369, 1475, 1, 'Glyph of the Orca'),
    (200101, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 1475, 1, 'Glyph of the Orca'),
    (200002, 268435456, 2048, 131072, 63, 101, 1, 0, 1, -1, 74, 0, 0, 1502, 12369, 292, 1, 'Glyph of the Zealot'),
    (200102, 192, 0, 0, 0, 101, 1, 21, 1, -1, 6, 1, 4, 0, 0, 292, 1, 'Glyph of the Zealot');

DELETE FROM `item_template` WHERE `entry` IN (100001, 100002);
INSERT INTO `item_template`
    (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `BuyPrice`, `SellPrice`,
     `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `stackable`,
     `bonding`, `description`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `Material`) VALUES
    (100001, 16, 0, 'Glyph of the Orca', 52559, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200001, 0, -1, -1),
    (100002, 16, 0, 'Glyph of the Zealot', 58828, 3, 0, 25000, 0, -1, -1, 60, 15, 1, 2, '', 200002, 0, -1, -1);

DELETE FROM `custom_glyphs` WHERE `glyph_id` IN (1501, 1502);
INSERT INTO `custom_glyphs` (`glyph_id`, `name`, `handler`, `handler_data`) VALUES
    (1501, 'Glyph of the Orca', 'display', '1066:21975'),
    (1502, 'Glyph of the Zealot', 'proc', 'zealot');

-- Add to the shared glyph drop pool
DELETE FROM `reference_loot_template` WHERE `Entry` = 90001 AND `Item` IN (100001, 100002);
INSERT INTO `reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
    (90001, 100001, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Orca'),
    (90001, 100002, 0, 0, 0, 1, 1, 1, 1, 'Custom Glyph - Glyph of the Zealot');
