#!/usr/bin/env python3
"""Generate the Random Enchantment seed SQL from the approved catalogue.

Reads docs/re_catalogue/mystic_enchants.csv (produced by parse_mystic_enchant.py),
keeps every enchant whose effect spell is a native 3.3.5 spell (the approved
"able to do" set — Ascension-custom spells are skipped), and writes the world-DB
seed file. Run from the module root:

    python3 tools/generate_re_sql.py
"""

import csv
import re
from pathlib import Path

MODULE = Path(__file__).resolve().parent.parent
CATALOGUE = MODULE / 'docs/re_catalogue/mystic_enchants.csv'
OUT = MODULE / 'data/sql/db-world/21_random_enchantments.sql'

# Their quality tags -> item-quality color indices (2 Uncommon .. 6 Artifact)
QUALITY = {'UNCOMMON': 2, 'RARE': 3, 'EPIC': 4, 'LEGENDARY': 5, 'ARTIFACT': 6}
ALL_SLOTS_MASK = 0xFFFF



def clean_tooltip(desc):
    desc = re.sub(r'@req:\d+:req@', '', desc)
    desc = re.sub(r'@s:\d+:[-\d]+', '', desc)
    desc = re.sub(r'@[^@\s]{1,40}@', '', desc)
    desc = re.sub(r'\|c[0-9a-fA-F]{8}', '', desc).replace('|r', '')
    desc = ' '.join(desc.split())
    return desc[:512]


def sql_escape(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


def main():
    rows = []
    seen_spells = set()
    for r in csv.DictReader(open(CATALOGUE)):
        if r['native'] != 'True':
            continue
        spell = int(r['spell'])
        if spell in seen_spells:
            continue  # rank-tier duplicates share the effect spell; keep first
        seen_spells.add(spell)
        quality = QUALITY.get(r['quality'])
        if quality is None:
            continue
        rows.append({
            'id': int(r['id']),
            'name': r['name'],
            'tooltip': clean_tooltip(r['desc']),
            'quality': quality,
            'weight': float(r['weight']) or 100.0,
            'min_level': max(1, int(r['level'])),
            'spell': spell,
        })

    rows.sort(key=lambda x: x['id'])

    lines = [
        '-- Random Enchantment (RE) system: enchant definitions.',
        '-- Generated by tools/generate_re_sql.py from docs/re_catalogue/mystic_enchants.csv',
        '-- (native-spell enchants only; handler \'aura\' applies handler_data as an aura while equipped).',
        '',
        'CREATE TABLE IF NOT EXISTS `custom_random_enchantments` (',
        '    `id` INT NOT NULL PRIMARY KEY,',
        '    `name` VARCHAR(100) NOT NULL,',
        '    `tooltip` VARCHAR(512) NOT NULL DEFAULT \'\',',
        '    `quality` TINYINT NOT NULL DEFAULT 2,',
        '    `weight` FLOAT NOT NULL DEFAULT 100,',
        '    `min_level` TINYINT UNSIGNED NOT NULL DEFAULT 1,',
        '    `slot_mask` INT NOT NULL DEFAULT 65535,',
        '    `handler` VARCHAR(32) NOT NULL DEFAULT \'aura\',',
        '    `handler_data` VARCHAR(255) NOT NULL DEFAULT \'\'',
        ') ENGINE=InnoDB;',
        '',
        'DELETE FROM `custom_random_enchantments`;',
        'INSERT INTO `custom_random_enchantments`',
        '    (`id`, `name`, `tooltip`, `quality`, `weight`, `min_level`, `slot_mask`, `handler`, `handler_data`) VALUES',
    ]
    values = []
    for e in rows:
        values.append(
            "    ({}, '{}', '{}', {}, {}, {}, {}, 'aura', '{}')".format(
                e['id'], sql_escape(e['name']), sql_escape(e['tooltip']),
                e['quality'], e['weight'], e['min_level'], ALL_SLOTS_MASK,
                e['spell']))
    lines.append(',\n'.join(values) + ';')
    lines.append('')

    OUT.write_text('\n'.join(lines))
    print(f'{len(rows)} enchants -> {OUT}')


if __name__ == '__main__':
    main()
